### ISSUE TITLE
stop pause resume not working 

### ISSUE THREAD

**Issue by hmd83** [MattVador/node-red-contrib-play-sound#1]
Hallo 
stop pause resume not working  
in node-red v0.15.3 raspberry pi

**Comment by MattVador** [comment]
Hi,

Could you please send me more details :
- nodejs version
- raspberry pi version (0, 1, 2, 3, A, B ...)
- log with errors

Thanks

**Comment by simatao** [comment]
Hi Matt,
the sound node plays mp3s fine, but I cannot stop the music. I use a inject node with msg.payload = "stop". It successfully removes the "playing" icon underneath the sound node and triggers the "stop" response on the sound node's output. So I guess the node understands the stop command, because it behaves differently when I send gibberish inputs. But, the music keeps playing nontheless.
I am using a raspberry Pi 3, all updated & upgraded and hdmi sound output. Node Version 6.11.1. Node Red version 0.17.4
Please help me fix this @MattVador . @hmd83 how did you do it?
Thanks
